services:
  - type: web
    name: tg-filestreambot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 -m WebStreamer
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: BIN_CHANNEL
        sync: false
      - key: PORT
        value: 8080
      - key: WEB_SERVER_BIND_ADDRESS
        value: 0.0.0.0
